---
- name: Install and configure Apache with a PHP web site
  hosts: all
  tasks:
    - name: Install Apache
      ansible.builtin.dnf:
        name: httpd

    - name: Install Apache PHP dependencies
      ansible.builtin.dnf:
        name:
          - php

    - name: Remove index.html
      ansible.builtin.file:
        name: /var/www/html/index.html
        state: absent

    - name: Put website in place
      ansible.builtin.unarchive:
        src: website.tar.gz
        dest: /var/www/html/
        owner: root
        group: root
        mode: 0644

    - name: Enable the Apache service
      ansible.builtin.service:
        name: httpd
        state: started
        enabled: true
